name: Build KSUD
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
          - target: x86_64-linux-android
          - target: x86_64-pc-windows-gnu # only for build
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
