name: Build Manager
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-ksud:
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
          - target: x86_64-linux-android
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
  build-manager:
    needs: build-ksud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup need_upload
      id: need_upload
      run: |
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          echo "UPLOAD=true" >> $GITHUB_OUTPUT
        else
          echo "UPLOAD=false" >> $GITHUB_OUTPUT
        fi
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    - name: Extract keystore
      if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/main' ) || github.ref_type == 'tag' }}
      run: |
        if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
          echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' >> sign.properties
          echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}' >> sign.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> sign.properties
          echo KEYSTORE_FILE='../key.jks' >> sign.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks
        fi
    - name: Download arm64 ksud
      uses: actions/download-artifact@v3
      with:
        name: ksud-aarch64-linux-android
        path: .
    - name: Download x86_64 ksud
      uses: actions/download-artifact@v3
      with:
        name: ksud-x86_64-linux-android
        path: .
    - name: Copy ksud to app jniLibs
      run: |
        mkdir -p app/src/main/jniLibs/arm64-v8a
        mkdir -p app/src/main/jniLibs/x86_64
        cp -f ../aarch64-linux-android/release/ksud ../manager/app/src/main/jniLibs/arm64-v8a/libksud.so
        cp -f ../x86_64-linux-android/release/ksud ../manager/app/src/main/jniLibs/x86_64/libksud.so
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assembleRelease
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: manager
        path: manager/app/build/outputs/apk/release/*.apk