name: Clippy check for pull request

on:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: giraffate/clippy-action@v1
        with:
          workdir: userspace/ksud
